stages:
  - build_docs
  - build
  - test
  - deploy

variables:
  PROJECT_GO_PATH: git.zam.io/wallet-backend/web-api
  EXECUTABLE_ENTRY_POINT: cmd/main/main.go
  EXECUTABLE_NAME: web-api

#============
# COMMON PART
#============
build:
  stage: build
  variables:
    GOROOT: /usr/lib/go-1.10/
    GOPATH: /var/opt/golang
    BUILD_OUT_DIR: $CI_PROJECT_DIR/build
    DEP_LOCK_FILE: glide.lock
  cache:
    key: build_$CI_COMMIT_REF_NAME
    paths:
    - vendor
  script:
    # prepare go-env
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    - export OLDGOPATH=$GOPATH
    - export GOPATH=`pwd`

    - mkdir -p $BUILD_OUT_DIR

    # copy all files into go-style path
    - mkdir -p vendor
    - mkdir -p .src/$PROJECT_GO_PATH
    - cp -r * .src/$PROJECT_GO_PATH
    - "[ -f vendor/$DEP_LOCK_FILE ] && cp vendor/$DEP_LOCK_FILE .src/$PROJECT_GO_PATH/"
    - mv .src src
    - cd src/$PROJECT_GO_PATH

    # install dependencies
    - glide install

    # build tests if they are present
    - tests_query=$( find -name '*_test.go | grep -v vendor' )
    - '[ ! -z "$tests_query" ] && ginkgo build -r .'
    - mkdir -p $BUILD_OUT_DIR/tests
    - '[ ! -z "$tests_query" ] && cp `find -name *.test` $BUILD_OUT_DIR/tests'

    # build binary into artifact
    - go build -o $BUILD_OUT_DIR/$EXECUTABLE_NAME $EXECUTABLE_ENTRY_POINT

    # copy migrations
    - mkdir -p $BUILD_OUT_DIR/migrations
    - cp db/migrations/* $BUILD_OUT_DIR/migrations

    # copy config generator
    - cp config_generator.sh $BUILD_OUT_DIR

    # cache vendor path
    - cp $DEP_LOCK_FILE $CI_PROJECT_DIR/vendor/
    - cp -r vendor/* $CI_PROJECT_DIR/vendor/
  tags:
    - build_srv
  artifacts:
    paths:
      - build

docs_build:
  stage: build_docs
  variables:
    OUT_FILE_NAME: $CI_COMMIT_REF_NAME.json
  script:
    - mkdir -p docs
    - npm install swagger-cli
    - ./node_modules/swagger-cli/bin/swagger-cli.js bundle docs/api/index.yaml > $OUT_FILE_NAME
    - cp $OUT_FILE_NAME docs/
  tags:
    - build_srv
  artifacts:
    paths:
      - docs
  cache:
    key: node_modules
    paths:
      - node_modules/
  only:
    - master
    - development

test:
  stage: test
  script:
    # export variables used by test to lookup migrations and db
    - export WA_DB_URI=$TESTING_DB_URI
    - export WA_MIGRATIONS_DIR=build/migrations

    # run them sequentially break if any of them failed
    - bash -c 'for TEST in $(find -name *.test); do ./$TEST; if [ $? -ne 0 ]; then break; fi; done'
  tags:
    - testing_srv
  dependencies:
    - build

deploy_on_staging:
  stage: deploy
  script:
    - export DEPLOY_DIR=$STAGING_DEPLOY_DIR/$EXECUTABLE_NAME

    # remove outdated binary and copy new one
    - mkdir -p $DEPLOY_DIR
    - rm -f $DEPLOY_DIR/$EXECUTABLE_NAME
    - cp build/$EXECUTABLE_NAME $DEPLOY_DIR
    - cp build/config_generator.sh $DEPLOY_DIR
    - cp -r build/migrations $DEPLOY_DIR

    # generate config
    - cd $DEPLOY_DIR
    - bash config_generator.sh > conf.yaml

    # trigger systemd to restart service by softly killing old instance
    - killall -1 $EXECUTABLE_NAME
  only:
    - master
  tags:
    - testing_srv

docs_deploy_on_staging:
  stage: deploy
  variables:
    DEPLOY_DIR: $STAGING_DEPLOY_DIR/docs/$EXECUTABLE_NAME/
    OUT_FILE_NAME: $CI_COMMIT_REF_NAME.json
  script:
    - mkdir -p $DEPLOY_DIR
    - cp docs/$OUT_FILE_NAME $DEPLOY_DIR
  tags:
    - testing_srv
  artifacts:
    paths:
      - docs
  only:
    - master
    - development