// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import notifications "git.zam.io/wallet-backend/web-api/internal/services/notifications"

// ISender is an autogenerated mock type for the ISender type
type ISender struct {
	mock.Mock
}

// Send provides a mock function with given fields: action, data, level
func (_m *ISender) Send(action string, data interface{}, level notifications.ImportanceLevel) error {
	ret := _m.Called(action, data, level)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, notifications.ImportanceLevel) error); ok {
		r0 = rf(action, data, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
