// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// ITransport is an autogenerated mock type for the ITransport type
type ITransport struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipient, body
func (_m *ITransport) Send(recipient string, body string) error {
	ret := _m.Called(recipient, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(recipient, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
